"""fix_import_conflict_lock_and_expires_at

Revision ID: 1a870f75396e
Revises: 1eb0c022a12d
Create Date: 2026-03-24 18:02:02.254257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a870f75396e'
down_revision: Union[str, Sequence[str], None] = '1eb0c022a12d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('import_conflicts_locked_by_job_id_fkey'), 'import_conflicts', type_='foreignkey')
    op.drop_column('import_conflicts', 'locked_by_job_id')
    op.alter_column('import_jobs', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_jobs', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('import_conflicts', sa.Column('locked_by_job_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('import_conflicts_locked_by_job_id_fkey'), 'import_conflicts', 'import_jobs', ['locked_by_job_id'], ['id'])
    # ### end Alembic commands ###
