"""import_system_tables_and_fks

Revision ID: 1eb0c022a12d
Revises: 4ca313a50e4a
Create Date: 2026-03-24 17:57:59.352853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eb0c022a12d'
down_revision: Union[str, Sequence[str], None] = '4ca313a50e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_mapping_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'entity_type', name='uq_mapping_template')
    )
    op.create_table('import_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_conflicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('import_record_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('locked_by_job_id', sa.Uuid(), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('merge_decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.ForeignKeyConstraint(['import_record_id'], ['import_records.id'], ),
    sa.ForeignKeyConstraint(['locked_by_job_id'], ['import_jobs.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_record_id')
    )
    op.add_column('assets', sa.Column('import_job_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_assets_import_job_id', 'assets', 'import_jobs', ['import_job_id'], ['id'])
    op.add_column('employees', sa.Column('import_job_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_employees_import_job_id', 'employees', 'import_jobs', ['import_job_id'], ['id'])
    op.add_column('locations', sa.Column('import_job_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_locations_import_job_id', 'locations', 'import_jobs', ['import_job_id'], ['id'])
    op.add_column('vendors', sa.Column('import_job_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_vendors_import_job_id', 'vendors', 'import_jobs', ['import_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_vendors_import_job_id', 'vendors', type_='foreignkey')
    op.drop_column('vendors', 'import_job_id')
    op.drop_constraint('fk_locations_import_job_id', 'locations', type_='foreignkey')
    op.drop_column('locations', 'import_job_id')
    op.drop_constraint('fk_employees_import_job_id', 'employees', type_='foreignkey')
    op.drop_column('employees', 'import_job_id')
    op.drop_constraint('fk_assets_import_job_id', 'assets', type_='foreignkey')
    op.drop_column('assets', 'import_job_id')
    op.drop_table('import_conflicts')
    op.drop_table('import_records')
    op.drop_table('import_mapping_templates')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
