"""add_asset_relations_jsonb

Revision ID: 477d1aa66bd4
Revises: d3cf4e7811be
Create Date: 2026-03-27 23:42:23.724584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '477d1aa66bd4'
down_revision: Union[str, Sequence[str], None] = 'd3cf4e7811be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset_relations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('locations', sa.Column('default_asset_relations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('organizations', sa.Column('default_asset_relations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('idx_assets_relations', 'assets', ['asset_relations'], postgresql_using='gin')
    op.create_index('idx_locations_default_relations', 'locations', ['default_asset_relations'], postgresql_using='gin')
    op.create_index('idx_organizations_default_relations', 'organizations', ['default_asset_relations'], postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_assets_relations', table_name='assets')
    op.drop_index('idx_locations_default_relations', table_name='locations')
    op.drop_index('idx_organizations_default_relations', table_name='organizations')
    op.drop_column('organizations', 'default_asset_relations')
    op.drop_column('locations', 'default_asset_relations')
    op.drop_column('assets', 'asset_relations')
    # ### end Alembic commands ###
