"""add_departments_and_org_regional_settings

Revision ID: 71c57d552979
Revises: 477d1aa66bd4
Create Date: 2026-03-27 23:45:54.314975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71c57d552979'
down_revision: Union[str, Sequence[str], None] = '477d1aa66bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('language_id', sa.Uuid(), nullable=True),
    sa.Column('default_asset_relations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_departments_parent', 'departments', ['parent_id'], unique=False)
    op.create_index('idx_departments_tenant_org', 'departments', ['tenant_id', 'organization_id'], unique=False)
    op.create_index('idx_dept_default_relations', 'departments', ['default_asset_relations'], postgresql_using='gin')
    op.drop_index(op.f('idx_assets_relations'), table_name='assets', postgresql_using='gin')
    op.add_column('employees', sa.Column('department_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    op.drop_index(op.f('idx_locations_default_relations'), table_name='locations', postgresql_using='gin')
    op.add_column('organizations', sa.Column('region_id', sa.Uuid(), nullable=True))
    op.add_column('organizations', sa.Column('language_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('idx_organizations_default_relations'), table_name='organizations', postgresql_using='gin')
    op.create_foreign_key(None, 'organizations', 'regions', ['region_id'], ['id'])
    op.create_foreign_key(None, 'organizations', 'languages', ['language_id'], ['id'])
    op.add_column('users', sa.Column('department_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'department_id')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_index(op.f('idx_organizations_default_relations'), 'organizations', ['default_asset_relations'], unique=False, postgresql_using='gin')
    op.drop_column('organizations', 'language_id')
    op.drop_column('organizations', 'region_id')
    op.create_index(op.f('idx_locations_default_relations'), 'locations', ['default_asset_relations'], unique=False, postgresql_using='gin')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'department_id')
    op.create_index(op.f('idx_assets_relations'), 'assets', ['asset_relations'], unique=False, postgresql_using='gin')
    op.drop_index('idx_dept_default_relations', table_name='departments')
    op.drop_index('idx_departments_tenant_org', table_name='departments')
    op.drop_index('idx_departments_parent', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
