"""add_i18n_tables

Revision ID: d3cf4e7811be
Revises: 6f0a8ed72451
Create Date: 2026-03-26 21:41:30.509082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3cf4e7811be'
down_revision: Union[str, Sequence[str], None] = '6f0a8ed72451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('babel_code', sa.String(length=20), nullable=False),
    sa.Column('text_direction', sa.String(length=3), nullable=False),
    sa.Column('plural_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalizations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('regions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_language_id', sa.Uuid(), nullable=False),
    sa.Column('decimal_separator', sa.String(length=1), nullable=False),
    sa.Column('thousands_separator', sa.String(length=1), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('csv_delimiter', sa.String(length=1), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('first_day_of_week', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('measurement_system', sa.String(length=10), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('region_identifier_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=True),
    sa.Column('checksum_method', sa.String(length=50), nullable=True),
    sa.Column('prefix', sa.String(length=5), nullable=True),
    sa.Column('applies_to', sa.String(length=10), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'code', name='uq_region_identifier_type')
    )
    op.create_table('tenant_regional_settings',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('decimal_separator', sa.String(length=1), nullable=True),
    sa.Column('thousands_separator', sa.String(length=1), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=True),
    sa.Column('csv_delimiter', sa.String(length=1), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('first_day_of_week', sa.String(length=3), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('measurement_system', sa.String(length=10), nullable=True),
    sa.Column('unit_display_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_regional_settings')
    op.drop_table('region_identifier_types')
    op.drop_table('user_settings')
    op.drop_table('regions')
    op.drop_table('languages')
    # ### end Alembic commands ###
